"""Small Qt-oriented localisation layer for BildBlick.

All catalogue data is bundled locally.  ``QCoreApplication.translate`` is
always consulted first, so generated Qt ``.qm`` catalogues can be added later
without changing callers; the compact built-in catalogue is the reliable
fallback for source and frozen builds.
"""
from __future__ import annotations

from PySide6.QtCore import QCoreApplication, QObject, QSettings
from PySide6.QtGui import QAction
from PySide6.QtWidgets import QApplication, QCheckBox, QComboBox, QDialog, QGroupBox, QLabel, QMainWindow, QMenu, QPushButton, QToolButton, QWidget

LANGUAGE_KEY = "interface/language"
LANGUAGES = {
    "de": "🇩🇪 Deutsch", "en": "🇬🇧 English", "fr": "🇫🇷 Français",
    "es": "🇪🇸 Español", "uk": "🇺🇦 Українська",
}

# Source strings deliberately remain German: technical EXIF tag names are not
# catalogue keys and therefore stay untouched.
CATALOGUE = {
    "en": {"Datei": "File", "Bearbeiten": "Edit", "Bild": "Image", "Ansicht": "View", "Navigation": "Navigation", "Werkzeuge": "Tools", "Hilfe": "Help", "Diashow": "Slideshow", "Sprache": "Language", "Bildinformationen": "Image Information", "Bildinformationen schließen (I)": "Close image information (I)", "Bildinformationen (I)": "Image information (I)", "Alle Metadaten": "All Metadata", "Keine EXIF-Daten vorhanden": "No EXIF data available", "BILD": "IMAGE", "KAMERA": "CAMERA", "AUFNAHME": "CAPTURE", "WEITERE EXIF-DATEN": "ADDITIONAL EXIF DATA", "Dateiname": "File name", "Dateipfad": "File path", "Dateigröße": "File size", "Dateiformat": "File format", "Abmessungen": "Dimensions", "Megapixel": "Megapixels", "Auflösung": "Resolution", "Ausrichtung": "Orientation", "Farbraum": "Color space", "Hersteller": "Manufacturer", "Kameramodell": "Camera model", "Objektiv": "Lens", "Aufnahmedatum": "Capture date", "Belichtungszeit": "Exposure time", "Blende": "Aperture", "Brennweite": "Focal length", "Vorheriges Bild": "Previous image", "Nächstes Bild": "Next image", "Vorherige PDF-Seite": "Previous PDF page", "Nächste PDF-Seite": "Next PDF page", "Drucken": "Print", "Mehrere Bilder drucken": "Print multiple images", "Kontaktabzug": "Contact sheet", "Dateiname anzeigen": "Show file name", "Aufnahmedatum anzeigen": "Show capture date", "Seitenzahl": "Page number", "Druckdatum": "Print date", "Schließen": "Close", "Abbrechen": "Cancel", "OK": "OK", "Kein Bild ausgewählt": "No image selected"},
    "fr": {"Datei": "Fichier", "Bearbeiten": "Édition", "Bild": "Image", "Ansicht": "Affichage", "Navigation": "Navigation", "Werkzeuge": "Outils", "Hilfe": "Aide", "Diashow": "Diaporama", "Sprache": "Langue", "Bildinformationen": "Informations sur l’image", "Bildinformationen schließen (I)": "Fermer les informations sur l’image (I)", "Bildinformationen (I)": "Informations sur l’image (I)", "Alle Metadaten": "Toutes les métadonnées", "Keine EXIF-Daten vorhanden": "Aucune donnée EXIF disponible", "BILD": "IMAGE", "KAMERA": "APPAREIL PHOTO", "AUFNAHME": "PRISE DE VUE", "WEITERE EXIF-DATEN": "DONNÉES EXIF SUPPLÉMENTAIRES", "Dateiname": "Nom du fichier", "Dateipfad": "Chemin du fichier", "Dateigröße": "Taille du fichier", "Dateiformat": "Format de fichier", "Abmessungen": "Dimensions", "Megapixel": "Mégapixels", "Auflösung": "Résolution", "Ausrichtung": "Orientation", "Farbraum": "Espace colorimétrique", "Hersteller": "Fabricant", "Kameramodell": "Modèle d’appareil", "Objektiv": "Objectif", "Aufnahmedatum": "Date de prise de vue", "Vorheriges Bild": "Image précédente", "Nächstes Bild": "Image suivante", "Vorherige PDF-Seite": "Page PDF précédente", "Nächste PDF-Seite": "Page PDF suivante", "Drucken": "Imprimer", "Mehrere Bilder drucken": "Imprimer plusieurs images", "Kontaktabzug": "Planche-contact", "Schließen": "Fermer", "Abbrechen": "Annuler", "Kein Bild ausgewählt": "Aucune image sélectionnée"},
    "es": {"Datei": "Archivo", "Bearbeiten": "Editar", "Bild": "Imagen", "Ansicht": "Ver", "Navigation": "Navegación", "Werkzeuge": "Herramientas", "Hilfe": "Ayuda", "Diashow": "Presentación", "Sprache": "Idioma", "Bildinformationen": "Información de la imagen", "Bildinformationen schließen (I)": "Cerrar información de la imagen (I)", "Bildinformationen (I)": "Información de la imagen (I)", "Alle Metadaten": "Todos los metadatos", "Keine EXIF-Daten vorhanden": "No hay datos EXIF disponibles", "BILD": "IMAGEN", "KAMERA": "CÁMARA", "AUFNAHME": "CAPTURA", "WEITERE EXIF-DATEN": "DATOS EXIF ADICIONALES", "Dateiname": "Nombre de archivo", "Dateipfad": "Ruta del archivo", "Dateigröße": "Tamaño del archivo", "Dateiformat": "Formato de archivo", "Abmessungen": "Dimensiones", "Megapixel": "Megapíxeles", "Auflösung": "Resolución", "Ausrichtung": "Orientación", "Farbraum": "Espacio de color", "Hersteller": "Fabricante", "Kameramodell": "Modelo de cámara", "Objektiv": "Objetivo", "Aufnahmedatum": "Fecha de captura", "Vorheriges Bild": "Imagen anterior", "Nächstes Bild": "Imagen siguiente", "Vorherige PDF-Seite": "Página PDF anterior", "Nächste PDF-Seite": "Página PDF siguiente", "Drucken": "Imprimir", "Mehrere Bilder drucken": "Imprimir varias imágenes", "Kontaktabzug": "Hoja de contactos", "Schließen": "Cerrar", "Abbrechen": "Cancelar", "Kein Bild ausgewählt": "Ninguna imagen seleccionada"},
    "uk": {"Datei": "Файл", "Bearbeiten": "Редагування", "Bild": "Зображення", "Ansicht": "Вигляд", "Navigation": "Навігація", "Werkzeuge": "Інструменти", "Hilfe": "Довідка", "Diashow": "Слайд-шоу", "Sprache": "Мова", "Bildinformationen": "Інформація про зображення", "Bildinformationen schließen (I)": "Закрити інформацію про зображення (I)", "Bildinformationen (I)": "Інформація про зображення (I)", "Alle Metadaten": "Усі метадані", "Keine EXIF-Daten vorhanden": "Дані EXIF відсутні", "BILD": "ЗОБРАЖЕННЯ", "KAMERA": "КАМЕРА", "AUFNAHME": "ЗЙОМКА", "WEITERE EXIF-DATEN": "ДОДАТКОВІ ДАНІ EXIF", "Dateiname": "Назва файлу", "Dateipfad": "Шлях до файлу", "Dateigröße": "Розмір файлу", "Dateiformat": "Формат файлу", "Abmessungen": "Розміри", "Megapixel": "Мегапікселі", "Auflösung": "Роздільність", "Ausrichtung": "Орієнтація", "Farbraum": "Колірний простір", "Hersteller": "Виробник", "Kameramodell": "Модель камери", "Objektiv": "Об’єктив", "Aufnahmedatum": "Дата зйомки", "Vorheriges Bild": "Попереднє зображення", "Nächstes Bild": "Наступне зображення", "Vorherige PDF-Seite": "Попередня сторінка PDF", "Nächste PDF-Seite": "Наступна сторінка PDF", "Drucken": "Друк", "Mehrere Bilder drucken": "Друк кількох зображень", "Kontaktabzug": "Контактний аркуш", "Schließen": "Закрити", "Abbrechen": "Скасувати", "Kein Bild ausgewählt": "Зображення не вибрано"},
}

_language = "de"

# Shared print/dialog wording.  Keeping this separate makes extending all
# five catalogues straightforward while preserving German as the source text.
for _code, _words in {
    "en": {"Bild oder Ordner hier ablegen": "Drop image or folder here", "Bildinformationen schließen": "Close image information", "Bitte gib einen Dateinamen ein.": "Please enter a file name.", "Der Dateiname darf weder „/“ noch Nullzeichen enthalten.": "The file name must not contain “/” or null characters.", "Dieser Dateiname ist nicht zulässig.": "This file name is not allowed.", "GPS": "GPS", "Kein Ordner": "No folder", "Ordner konnte nicht vollständig gelesen werden": "Folder could not be read completely"},
    "fr": {"(keine)": "(aucune)", "Ausgewählte Bilder verkleinert exportieren …": "Exporter les images sélectionnées en taille réduite …", "Bild in den Papierkorb verschieben": "Mettre l’image à la corbeille", "Bild oder Ordner hier ablegen": "Déposer une image ou un dossier ici", "Bildinformationen schließen": "Fermer les informations sur l’image", "Bisher: {name}": "Actuel : {name}", "Bitte gib einen Dateinamen ein.": "Saisissez un nom de fichier.", "Das dauerhafte Drehen animierter GIF-Dateien wird derzeit nicht unterstützt.": "La rotation permanente des GIF animés n’est pas encore prise en charge.", "Dateiendung: {extension}": "Extension : {extension}", "Dateivorgang fehlgeschlagen": "Opération sur le fichier échouée", "Der Dateiname darf weder „/“ noch Nullzeichen enthalten.": "Le nom de fichier ne doit contenir ni « / » ni caractère nul.", "Der Ordner ist schreibgeschützt oder nicht beschreibbar.": "Le dossier est en lecture seule ou non accessible en écriture.", "Der Speicherort konnte nicht geöffnet werden.": "L’emplacement n’a pas pu être ouvert.", "Dieser Dateiname ist nicht zulässig.": "Ce nom de fichier n’est pas autorisé.", "Dieses Bildformat wird nicht unterstützt.": "Ce format d’image n’est pas pris en charge.", "Drucken …": "Imprimer …", "Einige Bilder konnten nicht eingefügt werden.": "Certaines images n’ont pas pu être collées.", "Es wurden nur unterstützte Bilder aus dem Ordner des ersten Bildes geöffnet.": "Seules les images prises en charge du dossier de la première image ont été ouvertes.", "GPS": "GPS", "Kein Ordner": "Aucun dossier", "Mehrere Bilder drucken …": "Imprimer plusieurs images …", "Möchtest du die Drehung dauerhaft in der Originaldatei speichern?\n\nDie Bilddaten werden neu gespeichert. Dieser Vorgang kann in BildBlick nicht direkt rückgängig gemacht werden.": "Voulez-vous enregistrer définitivement la rotation dans le fichier original ?\n\nLes données de l’image seront enregistrées à nouveau. Cette opération ne peut pas être annulée directement dans BildBlick.", "OK": "OK", "Ordner konnte nicht vollständig gelesen werden": "Le dossier n’a pas pu être lu entièrement", "{name}: nicht verfügbar oder nicht unterstützt": "{name} : indisponible ou non pris en charge", "{name}: übersprungen": "{name} : ignoré"},
    "es": {"(keine)": "(ninguna)", "Ausgewählte Bilder verkleinert exportieren …": "Exportar imágenes seleccionadas reducidas …", "Bild in den Papierkorb verschieben": "Mover imagen a la papelera", "Bild oder Ordner hier ablegen": "Suelte aquí una imagen o carpeta", "Bildinformationen schließen": "Cerrar información de la imagen", "Bisher: {name}": "Actual: {name}", "Bitte gib einen Dateinamen ein.": "Introduzca un nombre de archivo.", "Das dauerhafte Drehen animierter GIF-Dateien wird derzeit nicht unterstützt.": "La rotación permanente de GIF animados aún no es compatible.", "Dateiendung: {extension}": "Extensión: {extension}", "Dateivorgang fehlgeschlagen": "Falló la operación de archivo", "Der Dateiname darf weder „/“ noch Nullzeichen enthalten.": "El nombre de archivo no puede contener «/» ni caracteres nulos.", "Der Ordner ist schreibgeschützt oder nicht beschreibbar.": "La carpeta es de solo lectura o no se puede escribir en ella.", "Der Speicherort konnte nicht geöffnet werden.": "No se pudo abrir la ubicación.", "Die Bilddatei wurde nicht gefunden.": "No se encontró el archivo de imagen.", "Dieser Dateiname ist nicht zulässig.": "Este nombre de archivo no es válido.", "Dieses Bildformat wird nicht unterstützt.": "Este formato de imagen no es compatible.", "Drucken …": "Imprimir …", "Einige Bilder konnten nicht eingefügt werden.": "No se pudieron pegar algunas imágenes.", "Es wurden nur unterstützte Bilder aus dem Ordner des ersten Bildes geöffnet.": "Solo se abrieron imágenes compatibles de la carpeta de la primera imagen.", "GPS": "GPS", "Kein Ordner": "Ninguna carpeta", "Mehrere Bilder drucken …": "Imprimir varias imágenes …", "Möchtest du die Drehung dauerhaft in der Originaldatei speichern?\n\nDie Bilddaten werden neu gespeichert. Dieser Vorgang kann in BildBlick nicht direkt rückgängig gemacht werden.": "¿Quieres guardar permanentemente la rotación en el archivo original?\n\nLos datos de imagen se guardarán de nuevo. Esta operación no se puede deshacer directamente en BildBlick.", "OK": "Aceptar", "Ordner konnte nicht vollständig gelesen werden": "No se pudo leer completamente la carpeta", "{name}: nicht verfügbar oder nicht unterstützt": "{name}: no disponible o no compatible", "{name}: übersmitten": "{name}: omitido", "{name}: übersprungen": "{name}: omitido"},
    "uk": {"(keine)": "(немає)", "Ausgewählte Bilder verkleinert exportieren …": "Експортувати вибрані зображення зі зменшенням …", "Bild in den Papierkorb verschieben": "Перемістити зображення до кошика", "Bild oder Ordner hier ablegen": "Перетягніть сюди зображення або теку", "Bildinformationen schließen": "Закрити інформацію про зображення", "Bisher: {name}": "Поточна: {name}", "Bitte gib einen Dateinamen ein.": "Введіть назву файлу.", "Das dauerhafte Drehen animierter GIF-Dateien wird derzeit nicht unterstützt.": "Постійний поворот анімованих GIF наразі не підтримується.", "Dateiendung: {extension}": "Розширення файлу: {extension}", "Dateivorgang fehlgeschlagen": "Помилка операції з файлом", "Der Dateiname darf weder „/“ noch Nullzeichen enthalten.": "Назва файлу не може містити «/» або нульові символи.", "Der Ordner ist schreibgeschützt oder nicht beschreibbar.": "Тека доступна лише для читання або недоступна для запису.", "Der Speicherort konnte nicht geöffnet werden.": "Не вдалося відкрити розташування.", "Die Bilddatei wurde nicht gefunden.": "Файл зображення не знайдено.", "Dieser Dateiname ist nicht zulässig.": "Така назва файлу не дозволена.", "Dieses Bildformat wird nicht unterstützt.": "Цей формат зображення не підтримується.", "Drucken …": "Друкувати …", "Einige Bilder konnten nicht eingefügt werden.": "Деякі зображення не вдалося вставити.", "Es wurden nur unterstützte Bilder aus dem Ordner des ersten Bildes geöffnet.": "Відкрито лише підтримувані зображення з теки першого зображення.", "GPS": "GPS", "Kein Ordner": "Немає теки", "Mehrere Bilder drucken …": "Друкувати кілька зображень …", "Möchtest du die Drehung dauerhaft in der Originaldatei speichern?\n\nDie Bilddaten werden neu gespeichert. Dieser Vorgang kann in BildBlick nicht direkt rückgängig gemacht werden.": "Зберегти поворот назавжди в оригінальному файлі?\n\nДані зображення буде збережено повторно. Цю операцію неможливо скасувати безпосередньо в BildBlick.", "OK": "Гаразд", "Ordner konnte nicht vollständig gelesen werden": "Не вдалося повністю прочитати теку", "{name}: nicht verfügbar oder nicht unterstützt": "{name}: недоступний або не підтримується", "{name}: übersprungen": "{name}: пропущено"},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Profil:": "Profile:", "Papierformat:": "Paper size:", "Ausrichtung:": "Orientation:", "Hochformat": "Portrait", "Querformat": "Landscape", "Automatisch": "Automatic", "Benutzerdefiniert": "Custom", "Quelle:": "Source:", "Aktuelles Bild": "Current image", "Markierte Bilder": "Selected images", "Alle Bilder": "All images", "Kopfzeile": "Header", "Titel": "Title", "Dateiname": "File name", "Aufnahmedatum": "Capture date", "Seitenzahl": "Page number", "Druckdatum": "Print date", "Randlosdruck": "Borderless printing", "Vorschau": "Preview", "Als PDF speichern …": "Save as PDF …", "Profil speichern": "Save profile", "Profil löschen": "Delete profile"},
    "fr": {"Profil:": "Profil :", "Papierformat:": "Format de papier :", "Ausrichtung:": "Orientation :", "Hochformat": "Portrait", "Querformat": "Paysage", "Automatisch": "Automatique", "Benutzerdefiniert": "Personnalisé", "Quelle:": "Source :", "Aktuelles Bild": "Image actuelle", "Markierte Bilder": "Images sélectionnées", "Alle Bilder": "Toutes les images", "Kopfzeile": "En-tête", "Titel": "Titre", "Dateiname": "Nom du fichier", "Aufnahmedatum": "Date de prise de vue", "Seitenzahl": "Numéro de page", "Druckdatum": "Date d’impression", "Vorschau": "Aperçu", "Als PDF speichern …": "Enregistrer au format PDF …", "Profil speichern": "Enregistrer le profil", "Profil löschen": "Supprimer le profil"},
    "es": {"Profil:": "Perfil:", "Papierformat:": "Tamaño de papel:", "Ausrichtung:": "Orientación:", "Hochformat": "Vertical", "Querformat": "Horizontal", "Automatisch": "Automático", "Benutzerdefiniert": "Personalizado", "Quelle:": "Origen:", "Aktuelles Bild": "Imagen actual", "Markierte Bilder": "Imágenes seleccionadas", "Alle Bilder": "Todas las imágenes", "Kopfzeile": "Encabezado", "Titel": "Título", "Dateiname": "Nombre de archivo", "Aufnahmedatum": "Fecha de captura", "Seitenzahl": "Número de página", "Druckdatum": "Fecha de impresión", "Vorschau": "Vista previa", "Als PDF speichern …": "Guardar como PDF …", "Profil speichern": "Guardar perfil", "Profil löschen": "Eliminar perfil"},
    "uk": {"Profil:": "Профіль:", "Papierformat:": "Формат паперу:", "Ausrichtung:": "Орієнтація:", "Hochformat": "Книжкова", "Querformat": "Альбомна", "Automatisch": "Автоматично", "Benutzerdefiniert": "Власний", "Quelle:": "Джерело:", "Aktuelles Bild": "Поточне зображення", "Markierte Bilder": "Вибрані зображення", "Alle Bilder": "Усі зображення", "Kopfzeile": "Верхній колонтитул", "Titel": "Заголовок", "Dateiname": "Назва файлу", "Aufnahmedatum": "Дата зйомки", "Seitenzahl": "Номер сторінки", "Druckdatum": "Дата друку", "Vorschau": "Попередній перегляд", "Als PDF speichern …": "Зберегти як PDF …", "Profil speichern": "Зберегти профіль", "Profil löschen": "Видалити профіль"},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Dateien werden ermittelt …": "Collecting files …", "0 von {count} Dateien geprüft": "0 of {count} files checked", "{checked} von {total} Dateien geprüft": "{checked} of {total} files checked", "Behalten": "Keep", "In den Papierkorb": "Move to Trash", "Alle anderen markieren": "Mark all others", "Markierung aufheben": "Clear selection", "Suche abgebrochen. Es wurden keine Dateien verändert.": "Search cancelled. No files were changed."},
    "fr": {"Dateien werden ermittelt …": "Collecte des fichiers …", "0 von {count} Dateien geprüft": "0 fichier sur {count} vérifié", "{checked} von {total} Dateien geprüft": "{checked} fichiers sur {total} vérifiés", "Behalten": "Conserver", "In den Papierkorb": "Mettre à la corbeille", "Alle anderen markieren": "Marquer tous les autres", "Markierung aufheben": "Effacer la sélection", "Suche abgebrochen. Es wurden keine Dateien verändert.": "Recherche annulée. Aucun fichier n’a été modifié."},
    "es": {"Dateien werden ermittelt …": "Recopilando archivos …", "0 von {count} Dateien geprüft": "0 de {count} archivos comprobados", "{checked} von {total} Dateien geprüft": "{checked} de {total} archivos comprobados", "Behalten": "Conservar", "In den Papierkorb": "Mover a la papelera", "Alle anderen markieren": "Marcar todos los demás", "Markierung aufheben": "Borrar selección", "Suche abgebrochen. Es wurden keine Dateien verändert.": "Búsqueda cancelada. No se modificó ningún archivo."},
    "uk": {"Dateien werden ermittelt …": "Збирання файлів …", "0 von {count} Dateien geprüft": "Перевірено 0 із {count} файлів", "{checked} von {total} Dateien geprüft": "Перевірено {checked} із {total} файлів", "Behalten": "Залишити", "In den Papierkorb": "До кошика", "Alle anderen markieren": "Позначити всі інші", "Markierung aufheben": "Зняти позначення", "Suche abgebrochen. Es wurden keine Dateien verändert.": "Пошук скасовано. Файли не змінено."},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Visuell gleiche/ähnliche Bilder": "Visually same/similar images", "Ähnlichkeit:": "Similarity:", "Streng": "Strict", "Normal": "Normal", "Großzügig": "Generous", "Visuell gleich": "Visually same", "Visuell ähnlich": "Visually similar"},
    "fr": {"Visuell gleiche/ähnliche Bilder": "Images visuellement identiques/similaires", "Ähnlichkeit:": "Similarité :", "Streng": "Strict", "Normal": "Normal", "Großzügig": "Large", "Visuell gleich": "Visuellement identiques", "Visuell ähnlich": "Visuellement similaires"},
    "es": {"Visuell gleiche/ähnliche Bilder": "Imágenes visualmente iguales/similares", "Ähnlichkeit:": "Similitud:", "Streng": "Estricto", "Normal": "Normal", "Großzügig": "Amplio", "Visuell gleich": "Visualmente iguales", "Visuell ähnlich": "Visualmente similares"},
    "uk": {"Visuell gleiche/ähnliche Bilder": "Візуально однакові/схожі зображення", "Ähnlichkeit:": "Схожість:", "Streng": "Суворо", "Normal": "Звичайно", "Großzügig": "Широко", "Visuell gleich": "Візуально однакові", "Visuell ähnlich": "Візуально схожі"},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Gleicher Dateiname": "Same file name", "Exakt identisch": "Exactly identical", "Zusätzlich: gleicher Dateiname": "Also: same file name", "Keine Suchart ausgewählt": "No search type selected", "Bitte wählen Sie mindestens eine Suchart aus.": "Please select at least one search type."},
    "fr": {"Gleicher Dateiname": "Même nom de fichier", "Exakt identisch": "Exactement identique", "Zusätzlich: gleicher Dateiname": "Également : même nom de fichier", "Keine Suchart ausgewählt": "Aucun type de recherche sélectionné", "Bitte wählen Sie mindestens eine Suchart aus.": "Sélectionnez au moins un type de recherche."},
    "es": {"Gleicher Dateiname": "Mismo nombre de archivo", "Exakt identisch": "Exactamente idéntico", "Zusätzlich: gleicher Dateiname": "También: mismo nombre de archivo", "Keine Suchart ausgewählt": "No se seleccionó tipo de búsqueda", "Bitte wählen Sie mindestens eine Suchart aus.": "Seleccione al menos un tipo de búsqueda."},
    "uk": {"Gleicher Dateiname": "Однакова назва файлу", "Exakt identisch": "Точно ідентичні", "Zusätzlich: gleicher Dateiname": "Також: однакова назва файлу", "Keine Suchart ausgewählt": "Не вибрано тип пошуку", "Bitte wählen Sie mindestens eine Suchart aus.": "Виберіть принаймні один тип пошуку."},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Suchordner": "Search folders", "Ordner hinzufügen …": "Add folder …", "Entfernen": "Remove", "Kein Suchordner ausgewählt": "No search folder selected", "Bitte fügen Sie mindestens einen Suchordner hinzu.": "Please add at least one search folder."},
    "fr": {"Suchordner": "Dossiers de recherche", "Ordner hinzufügen …": "Ajouter un dossier …", "Entfernen": "Supprimer", "Kein Suchordner ausgewählt": "Aucun dossier de recherche sélectionné", "Bitte fügen Sie mindestens einen Suchordner hinzu.": "Ajoutez au moins un dossier de recherche."},
    "es": {"Suchordner": "Carpetas de búsqueda", "Ordner hinzufügen …": "Añadir carpeta …", "Entfernen": "Quitar", "Kein Suchordner ausgewählt": "No hay carpeta de búsqueda seleccionada", "Bitte fügen Sie mindestens einen Suchordner hinzu.": "Añada al menos una carpeta de búsqueda."},
    "uk": {"Suchordner": "Теки пошуку", "Ordner hinzufügen …": "Додати теку …", "Entfernen": "Вилучити", "Kein Suchordner ausgewählt": "Не вибрано теку пошуку", "Bitte fügen Sie mindestens einen Suchordner hinzu.": "Додайте принаймні одну теку пошуку."},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Für das Überschreiben der Originaldatei verwenden Sie bitte „Drehung im Original speichern …“.": "To overwrite the original file, use “Save rotation in original …”.", "Die Originaldatei ist schreibgeschützt oder es fehlen Schreibrechte.": "The original file is read-only or write permission is missing.", "Es wurden keine Dateien oder Ordner abgelegt.": "No files or folders were dropped.", "Bitte legen Sie entweder einen einzelnen Ordner oder Bilddateien ab.": "Please drop either a single folder or image files."},
    "fr": {"Für das Überschreiben der Originaldatei verwenden Sie bitte „Drehung im Original speichern …“.": "Pour écraser le fichier original, utilisez « Enregistrer la rotation dans l’original … ».", "Die Originaldatei ist schreibgeschützt oder es fehlen Schreibrechte.": "Le fichier original est en lecture seule ou les droits d’écriture manquent.", "Es wurden keine Dateien oder Ordner abgelegt.": "Aucun fichier ni dossier n’a été déposé.", "Bitte legen Sie entweder einen einzelnen Ordner oder Bilddateien ab.": "Déposez un seul dossier ou des fichiers image."},
    "es": {"Für das Überschreiben der Originaldatei verwenden Sie bitte „Drehung im Original speichern …“.": "Para sobrescribir el archivo original, use « Guardar rotación en el original … ».", "Die Originaldatei ist schreibgeschützt oder es fehlen Schreibrechte.": "El archivo original es de solo lectura o falta permiso de escritura.", "Es wurden keine Dateien oder Ordner abgelegt.": "No se soltaron archivos ni carpetas.", "Bitte legen Sie entweder einen einzelnen Ordner oder Bilddateien ab.": "Suelte una sola carpeta o archivos de imagen."},
    "uk": {"Für das Überschreiben der Originaldatei verwenden Sie bitte „Drehung im Original speichern …“.": "Щоб перезаписати оригінальний файл, скористайтеся «Зберегти поворот в оригіналі …».", "Die Originaldatei ist schreibgeschützt oder es fehlen Schreibrechte.": "Оригінальний файл доступний лише для читання або немає прав на запис.", "Es wurden keine Dateien oder Ordner abgelegt.": "Не додано жодного файлу чи теки.", "Bitte legen Sie entweder einen einzelnen Ordner oder Bilddateien ab.": "Додайте одну теку або файли зображень."},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Der Zielordner konnte nicht im Dateimanager geöffnet werden.": "The destination folder could not be opened in the file manager.", "Der neue Dateiname ist mit dem bisherigen Namen identisch.": "The new file name is the same as the current name.", "Eine Datei mit diesem Namen existiert bereits.": "A file with this name already exists.", "Die Bilddatei konnte nicht umbenannt werden.": "The image file could not be renamed.", "Der übergeordnete Ordner ist nicht erreichbar.": "The parent folder is not accessible.", "Weder Nemo noch ein anderer Dateimanager konnte gestartet werden.": "Neither Nemo nor another file manager could be started.", "{name}: {detail}": "{name}: {detail}", "Einige Bilder konnten nicht in den Papierkorb verschoben werden.": "Some images could not be moved to Trash.", "Ordner konnte nicht gelesen werden": "Folder could not be read", "Technische Details: {detail}": "Technical details: {detail}"},
    "fr": {"Der Zielordner konnte nicht im Dateimanager geöffnet werden.": "Le dossier de destination n’a pas pu être ouvert dans le gestionnaire de fichiers.", "Der neue Dateiname ist mit dem bisherigen Namen identisch.": "Le nouveau nom de fichier est identique au nom actuel.", "Eine Datei mit diesem Namen existiert bereits.": "Un fichier portant ce nom existe déjà.", "Die Bilddatei konnte nicht umbenannt werden.": "Le fichier image n’a pas pu être renommé.", "Der übergeordnete Ordner ist nicht erreichbar.": "Le dossier parent est inaccessible.", "Weder Nemo noch ein anderer Dateimanager konnte gestartet werden.": "Ni Nemo ni un autre gestionnaire de fichiers n’a pu être lancé.", "{name}: {detail}": "{name} : {detail}", "Einige Bilder konnten nicht in den Papierkorb verschoben werden.": "Certaines images n’ont pas pu être mises à la corbeille.", "Ordner konnte nicht gelesen werden": "Le dossier n’a pas pu être lu", "Technische Details: {detail}": "Détails techniques : {detail}"},
    "es": {"Der Zielordner konnte nicht im Dateimanager geöffnet werden.": "No se pudo abrir la carpeta de destino en el gestor de archivos.", "Der neue Dateiname ist mit dem bisherigen Namen identisch.": "El nuevo nombre de archivo es igual al actual.", "Eine Datei mit diesem Namen existiert bereits.": "Ya existe un archivo con este nombre.", "Die Bilddatei konnte nicht umbenannt werden.": "No se pudo cambiar el nombre del archivo de imagen.", "Der übergeordnete Ordner ist nicht erreichbar.": "No se puede acceder a la carpeta superior.", "Weder Nemo noch ein anderer Dateimanager konnte gestartet werden.": "No se pudo iniciar Nemo ni otro gestor de archivos.", "{name}: {detail}": "{name}: {detail}", "Einige Bilder konnten nicht in den Papierkorb verschoben werden.": "No se pudieron mover algunas imágenes a la papelera.", "Ordner konnte nicht gelesen werden": "No se pudo leer la carpeta", "Technische Details: {detail}": "Detalles técnicos: {detail}"},
    "uk": {"Der Zielordner konnte nicht im Dateimanager geöffnet werden.": "Не вдалося відкрити теку призначення у файловому менеджері.", "Der neue Dateiname ist mit dem bisherigen Namen identisch.": "Нова назва файлу збігається з поточною.", "Eine Datei mit diesem Namen existiert bereits.": "Файл із такою назвою вже існує.", "Die Bilddatei konnte nicht umbenannt werden.": "Не вдалося перейменувати файл зображення.", "Der übergeordnete Ordner ist nicht erreichbar.": "Батьківська тека недоступна.", "Weder Nemo noch ein anderer Dateimanager konnte gestartet werden.": "Не вдалося запустити Nemo чи інший файловий менеджер.", "{name}: {detail}": "{name}: {detail}", "Einige Bilder konnten nicht in den Papierkorb verschoben werden.": "Не вдалося перемістити деякі зображення до кошика.", "Ordner konnte nicht gelesen werden": "Не вдалося прочитати теку", "Technische Details: {detail}": "Технічні відомості: {detail}"},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Ablage nicht möglich": "Drop failed", "Die abgelegten Elemente können nicht geöffnet werden.": "The dropped items could not be opened.", "Nicht alle Elemente geöffnet": "Not all items opened", "Es wurden nur unterstützte Bilder aus dem Ordner des ersten Bildes geöffnet.": "Only supported images from the first image’s folder were opened.", "Drehung speichern": "Save rotation", "Das dauerhafte Drehen animierter GIF-Dateien wird derzeit nicht unterstützt.": "Saving rotation for animated GIF files is not supported.", "Gedrehte Kopie speichern": "Save rotated copy", "Datei überschreiben": "Overwrite file", "Die gewählte Datei ist bereits vorhanden.": "The selected file already exists.", "Überschreiben": "Overwrite", "Drehung im Original speichern": "Save rotation in original", "Möchtest du die Drehung dauerhaft in der Originaldatei speichern?\n\nDie Bilddaten werden neu gespeichert. Dieser Vorgang kann in BildBlick nicht direkt rückgängig gemacht werden.": "Do you want to permanently save the rotation in the original file?\n\nThe image data will be saved again. This cannot be undone directly in BildBlick.", "Original überschreiben": "Overwrite original", "Drehung konnte nicht gespeichert werden": "Rotation could not be saved", "Das gedrehte Bild konnte nicht gespeichert werden.": "The rotated image could not be saved."},
    "fr": {"Im Zielordner ist bereits eine Datei mit diesem Namen vorhanden.": "Un fichier portant ce nom existe déjà dans le dossier de destination.", "Zieldatei ersetzen": "Remplacer le fichier de destination", "Möchtest du diese Zieldatei wirklich ersetzen?": "Voulez-vous vraiment remplacer ce fichier de destination ?", "Für alle weiteren Konflikte übernehmen": "Appliquer aux conflits suivants", "Ablage nicht möglich": "Dépôt impossible", "Die abgelegten Elemente können nicht geöffnet werden.": "Les éléments déposés ne peuvent pas être ouverts.", "Nicht alle Elemente geöffnet": "Tous les éléments n’ont pas été ouverts", "Drehung speichern": "Enregistrer la rotation", "Gedrehte Kopie speichern": "Enregistrer une copie pivotée", "Datei überschreiben": "Écraser le fichier", "Die gewählte Datei ist bereits vorhanden.": "Le fichier choisi existe déjà.", "Überschreiben": "Écraser", "Drehung im Original speichern": "Enregistrer la rotation dans l’original", "Original überschreiben": "Écraser l’original", "Drehung konnte nicht gespeichert werden": "La rotation n’a pas pu être enregistrée", "Das gedrehte Bild konnte nicht gespeichert werden.": "L’image pivotée n’a pas pu être enregistrée."},
    "es": {"Im Zielordner ist bereits eine Datei mit diesem Namen vorhanden.": "Ya existe un archivo con este nombre en la carpeta de destino.", "Zieldatei ersetzen": "Reemplazar archivo de destino", "Möchtest du diese Zieldatei wirklich ersetzen?": "¿Quieres reemplazar realmente este archivo de destino?", "Für alle weiteren Konflikte übernehmen": "Aplicar a los demás conflictos", "Ablage nicht möglich": "No se pudo soltar", "Die abgelegten Elemente können nicht geöffnet werden.": "No se pueden abrir los elementos soltados.", "Nicht alle Elemente geöffnet": "No se abrieron todos los elementos", "Drehung speichern": "Guardar rotación", "Gedrehte Kopie speichern": "Guardar copia girada", "Datei überschreiben": "Sobrescribir archivo", "Die gewählte Datei ist bereits vorhanden.": "El archivo seleccionado ya existe.", "Überschreiben": "Sobrescribir", "Drehung im Original speichern": "Guardar rotación en el original", "Original überschreiben": "Sobrescribir original", "Drehung konnte nicht gespeichert werden": "No se pudo guardar la rotación", "Das gedrehte Bild konnte nicht gespeichert werden.": "No se pudo guardar la imagen girada."},
    "uk": {"Im Zielordner ist bereits eine Datei mit diesem Namen vorhanden.": "У теці призначення вже є файл із такою назвою.", "Zieldatei ersetzen": "Замінити файл призначення", "Möchtest du diese Zieldatei wirklich ersetzen?": "Справді замінити цей файл призначення?", "Für alle weiteren Konflikte übernehmen": "Застосувати до всіх наступних конфліктів", "Ablage nicht möglich": "Не вдалося додати", "Die abgelegten Elemente können nicht geöffnet werden.": "Не вдалося відкрити додані елементи.", "Nicht alle Elemente geöffnet": "Відкрито не всі елементи", "Drehung speichern": "Зберегти поворот", "Gedrehte Kopie speichern": "Зберегти повернуту копію", "Datei überschreiben": "Перезаписати файл", "Die gewählte Datei ist bereits vorhanden.": "Вибраний файл уже існує.", "Überschreiben": "Перезаписати", "Drehung im Original speichern": "Зберегти поворот в оригіналі", "Original überschreiben": "Перезаписати оригінал", "Drehung konnte nicht gespeichert werden": "Не вдалося зберегти поворот", "Das gedrehte Bild konnte nicht gespeichert werden.": "Не вдалося зберегти повернуте зображення."},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Umbenennen …": "Rename …", "Ausgewählte Bilder verkleinert exportieren …": "Export selected images resized …", "Drucken …": "Print …", "Mehrere Bilder drucken …": "Print multiple images …", "Beenden": "Quit", "Alles auswählen": "Select all", "Kopieren": "Copy", "Ausschneiden": "Cut", "Einfügen": "Paste", "In den Papierkorb verschieben": "Move to Trash", "In den Papierkorb": "Move to Trash", "Im Dateimanager anzeigen": "Show in File Manager", "Bild umbenennen": "Rename image", "Die Datei wurde nicht gefunden.": "The file was not found.", "Die Bilddatei wurde nicht gefunden.": "The image file was not found.", "Dieses Bildformat wird nicht unterstützt.": "This image format is not supported.", "Der Ordner ist schreibgeschützt oder nicht beschreibbar.": "The folder is read-only or not writable.", "Bisher: {name}": "Current: {name}", "Neuer Name:": "New name:", "Dateiendung: {extension}": "File extension: {extension}", "(keine)": "(none)", "Dateivorgang fehlgeschlagen": "File operation failed", "Datei bereits vorhanden": "File already exists", "Im Zielordner ist bereits eine Datei mit diesem Namen vorhanden.": "A file with this name already exists in the destination folder.", "Datei ersetzen": "Replace file", "Beide behalten": "Keep both", "Überspringen": "Skip", "Für alle weiteren Konflikte übernehmen": "Apply to all further conflicts", "Zieldatei ersetzen": "Replace destination file", "Möchtest du diese Zieldatei wirklich ersetzen?": "Do you really want to replace this destination file?", "{name}: nicht verfügbar oder nicht unterstützt": "{name}: unavailable or unsupported", "{name}: übersprungen": "{name}: skipped", "Einige Bilder konnten nicht eingefügt werden.": "Some images could not be pasted.", "Bild in den Papierkorb verschieben": "Move image to Trash", "Möchtest du dieses Bild in den Papierkorb verschieben?": "Do you want to move this image to Trash?", "Möchtest du die ausgewählten {count} Bilder in den Papierkorb verschieben?": "Do you want to move the selected {count} images to Trash?", "Ordner konnte nicht geöffnet werden": "Folder could not be opened", "Der Ordner kann nicht geöffnet werden.": "The folder could not be opened.", "Der Speicherort konnte nicht geöffnet werden.": "The location could not be opened."},
    "fr": {"Umbenennen …": "Renommer …", "Beenden": "Quitter", "Alles auswählen": "Tout sélectionner", "Kopieren": "Copier", "Ausschneiden": "Couper", "Einfügen": "Coller", "In den Papierkorb verschieben": "Mettre à la corbeille", "In den Papierkorb": "Mettre à la corbeille", "Im Dateimanager anzeigen": "Afficher dans le gestionnaire de fichiers", "Bild umbenennen": "Renommer l’image", "Die Datei wurde nicht gefunden.": "Le fichier est introuvable.", "Die Bilddatei wurde nicht gefunden.": "Le fichier image est introuvable.", "Neuer Name:": "Nouveau nom :", "Datei bereits vorhanden": "Le fichier existe déjà", "Datei ersetzen": "Remplacer le fichier", "Beide behalten": "Conserver les deux", "Überspringen": "Ignorer", "Möchtest du dieses Bild in den Papierkorb verschieben?": "Voulez-vous mettre cette image à la corbeille ?", "Möchtest du die ausgewählten {count} Bilder in den Papierkorb verschieben?": "Voulez-vous mettre les {count} images sélectionnées à la corbeille ?", "Ordner konnte nicht geöffnet werden": "Le dossier n’a pas pu être ouvert", "Der Ordner kann nicht geöffnet werden.": "Le dossier ne peut pas être ouvert."},
    "es": {"Umbenennen …": "Cambiar nombre …", "Beenden": "Salir", "Alles auswählen": "Seleccionar todo", "Kopieren": "Copiar", "Ausschneiden": "Cortar", "Einfügen": "Pegar", "In den Papierkorb verschieben": "Mover a la papelera", "In den Papierkorb": "Mover a la papelera", "Im Dateimanager anzeigen": "Mostrar en el gestor de archivos", "Bild umbenennen": "Cambiar nombre de imagen", "Die Datei wurde nicht gefunden.": "No se encontró el archivo.", "Neuer Name:": "Nuevo nombre:", "Datei bereits vorhanden": "El archivo ya existe", "Datei ersetzen": "Reemplazar archivo", "Beide behalten": "Conservar ambos", "Überspringen": "Omitir", "Möchtest du dieses Bild in den Papierkorb verschieben?": "¿Quieres mover esta imagen a la papelera?", "Möchtest du die ausgewählten {count} Bilder in den Papierkorb verschieben?": "¿Quieres mover las {count} imágenes seleccionadas a la papelera?", "Ordner konnte nicht geöffnet werden": "No se pudo abrir la carpeta", "Der Ordner kann nicht geöffnet werden.": "No se puede abrir la carpeta."},
    "uk": {"Umbenennen …": "Перейменувати …", "Beenden": "Вийти", "Alles auswählen": "Вибрати все", "Kopieren": "Копіювати", "Ausschneiden": "Вирізати", "Einfügen": "Вставити", "In den Papierkorb verschieben": "Перемістити до кошика", "In den Papierkorb": "До кошика", "Im Dateimanager anzeigen": "Показати у файловому менеджері", "Bild umbenennen": "Перейменувати зображення", "Die Datei wurde nicht gefunden.": "Файл не знайдено.", "Neuer Name:": "Нова назва:", "Datei bereits vorhanden": "Файл уже існує", "Datei ersetzen": "Замінити файл", "Beide behalten": "Зберегти обидва", "Überspringen": "Пропустити", "Möchtest du dieses Bild in den Papierkorb verschieben?": "Перемістити це зображення до кошика?", "Möchtest du die ausgewählten {count} Bilder in den Papierkorb verschieben?": "Перемістити вибрані зображення ({count}) до кошика?", "Ordner konnte nicht geöffnet werden": "Не вдалося відкрити теку", "Der Ordner kann nicht geöffnet werden.": "Не вдалося відкрити теку."},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Die PDF-Datei wurde nicht gefunden.": "The PDF file was not found.", "Die Datei ist keine gültige PDF.": "The file is not a valid PDF.", "Die PDF ist passwortgeschützt.": "The PDF is password protected.", "Die PDF-Verschlüsselung wird nicht unterstützt.": "PDF encryption is not supported.", "Die PDF konnte nicht geöffnet werden.": "The PDF could not be opened.", "Die PDF enthält keine Seiten.": "The PDF contains no pages.", "Ordner auswählen …": "Select folder …", "Unterordner einbeziehen": "Include subfolders", "Suche starten": "Start search", "Datei / Gruppe": "File / group", "Pfad": "Path", "Größe": "Size", "Geändert": "Modified", "Behalten": "Keep", "Papierkorb": "Trash"},
    "fr": {"Die PDF-Datei wurde nicht gefunden.": "Le fichier PDF est introuvable.", "Die Datei ist keine gültige PDF.": "Le fichier n’est pas un PDF valide.", "Die PDF ist passwortgeschützt.": "Le PDF est protégé par mot de passe.", "Die PDF-Verschlüsselung wird nicht unterstützt.": "Le chiffrement PDF n’est pas pris en charge.", "Die PDF konnte nicht geöffnet werden.": "Le PDF n’a pas pu être ouvert.", "Die PDF enthält keine Seiten.": "Le PDF ne contient aucune page.", "Ordner auswählen …": "Choisir un dossier …", "Unterordner einbeziehen": "Inclure les sous-dossiers", "Suche starten": "Démarrer la recherche", "Datei / Gruppe": "Fichier / groupe", "Pfad": "Chemin", "Größe": "Taille", "Geändert": "Modifié", "Behalten": "Conserver", "Papierkorb": "Corbeille"},
    "es": {"Die PDF-Datei wurde nicht gefunden.": "No se encontró el archivo PDF.", "Die Datei ist keine gültige PDF.": "El archivo no es un PDF válido.", "Die PDF ist passwortgeschützt.": "El PDF está protegido con contraseña.", "Die PDF-Verschlüsselung wird nicht unterstützt.": "No se admite el cifrado del PDF.", "Die PDF konnte nicht geöffnet werden.": "No se pudo abrir el PDF.", "Die PDF enthält keine Seiten.": "El PDF no contiene páginas.", "Ordner auswählen …": "Seleccionar carpeta …", "Unterordner einbeziehen": "Incluir subcarpetas", "Suche starten": "Iniciar búsqueda", "Datei / Gruppe": "Archivo / grupo", "Pfad": "Ruta", "Größe": "Tamaño", "Geändert": "Modificado", "Behalten": "Conservar", "Papierkorb": "Papelera"},
    "uk": {"Die PDF-Datei wurde nicht gefunden.": "Файл PDF не знайдено.", "Die Datei ist keine gültige PDF.": "Файл не є дійсним PDF.", "Die PDF ist passwortgeschützt.": "PDF захищено паролем.", "Die PDF-Verschlüsselung wird nicht unterstützt.": "Шифрування PDF не підтримується.", "Die PDF konnte nicht geöffnet werden.": "Не вдалося відкрити PDF.", "Die PDF enthält keine Seiten.": "PDF не містить сторінок.", "Ordner auswählen …": "Вибрати теку …", "Unterordner einbeziehen": "Включати вкладені теки", "Suche starten": "Почати пошук", "Datei / Gruppe": "Файл / група", "Pfad": "Шлях", "Größe": "Розмір", "Geändert": "Змінено", "Behalten": "Залишити", "Papierkorb": "Кошик"},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {
        "Doppelte Bilder finden": "Find duplicate images", "Suche läuft …": "Search running …", "Es wurden keine Dateien verändert.": "No files were changed.",
        "Markiere zuerst mindestens eine Datei in der Spalte Papierkorb.": "First select at least one file in the Trash column.", "Keine Auswahl": "No selection", "Es sind keine Dateien für den Papierkorb ausgewählt.": "No files are selected for the Trash.",
        "Dateien in den Papierkorb verschieben": "Move files to Trash", "Möchtest du die ausgewählten {count} Dateien in den Papierkorb verschieben?\n\nMindestens eine Datei jeder Duplikatgruppe bleibt erhalten.": "Do you want to move the selected {count} files to Trash?\n\nAt least one file in each duplicate group will be kept.",
        "Theoretisch freigebbarer Speicherplatz: {size}": "Theoretically reclaimable space: {size}", "{count} identische Dateien": "{count} identical files", "Keine doppelten Dateien mehr vorhanden.": "No duplicate files remain.",
        "{groups} verbleibende Duplikatgruppen · {files} verbleibende doppelte Dateien · {size} freigewordener Speicherplatz": "{groups} remaining duplicate groups · {files} remaining duplicate files · {size} space freed",
        "{count} Datei wurde in den Papierkorb verschoben.": "{count} file was moved to Trash.", "{count} Dateien wurden in den Papierkorb verschoben.": "{count} files were moved to Trash.", "Keine Datei verschoben": "No file moved", "Nicht alle Dateien wurden verschoben": "Not all files were moved",
        "Keine Datei konnte in den Papierkorb verschoben werden.": "No file could be moved to Trash.", "Einige Dateien konnten nicht in den Papierkorb verschoben werden.": "Some files could not be moved to Trash.", "Suche wird abgebrochen …": "Cancelling search …",
        "{reason}: {count}": "{reason}: {count}", "Zusätzlich: {reasons}": "Also: {reasons}", "Theoretisch einsparbar: {size}": "Theoretically reclaimable: {size}",
        "{examined} Bilddateien untersucht · {groups} Duplikatgruppen · {files} mehrfach vorhandene Dateien · {size} theoretisch freigebbar · {skipped} übersprungen oder fehlerhaft": "{examined} image files examined · {groups} duplicate groups · {files} duplicate files · {size} theoretically reclaimable · {skipped} skipped or faulty",
    },
    "fr": {
        "Doppelte Bilder finden": "Rechercher des images en double", "Suche läuft …": "Recherche en cours …", "Es wurden keine Dateien verändert.": "Aucun fichier n’a été modifié.",
        "Markiere zuerst mindestens eine Datei in der Spalte Papierkorb.": "Sélectionnez d’abord au moins un fichier dans la colonne Corbeille.", "Keine Auswahl": "Aucune sélection", "Es sind keine Dateien für den Papierkorb ausgewählt.": "Aucun fichier n’est sélectionné pour la corbeille.",
        "Dateien in den Papierkorb verschieben": "Mettre les fichiers à la corbeille", "Möchtest du die ausgewählten {count} Dateien in den Papierkorb verschieben?\n\nMindestens eine Datei jeder Duplikatgruppe bleibt erhalten.": "Voulez-vous mettre les {count} fichiers sélectionnés à la corbeille ?\n\nAu moins un fichier de chaque groupe de doublons sera conservé.",
        "Theoretisch freigebbarer Speicherplatz: {size}": "Espace théoriquement libérable : {size}", "{count} identische Dateien": "{count} fichiers identiques", "Keine doppelten Dateien mehr vorhanden.": "Il ne reste aucun fichier en double.",
        "{groups} verbleibende Duplikatgruppen · {files} verbleibende doppelte Dateien · {size} freigewordener Speicherplatz": "{groups} groupes de doublons restants · {files} fichiers en double restants · {size} d’espace libéré",
        "{count} Datei wurde in den Papierkorb verschoben.": "{count} fichier a été mis à la corbeille.", "{count} Dateien wurden in den Papierkorb verschoben.": "{count} fichiers ont été mis à la corbeille.", "Keine Datei verschoben": "Aucun fichier déplacé", "Nicht alle Dateien wurden verschoben": "Tous les fichiers n’ont pas été déplacés",
        "Keine Datei konnte in den Papierkorb verschoben werden.": "Aucun fichier n’a pu être mis à la corbeille.", "Einige Dateien konnten nicht in den Papierkorb verschoben werden.": "Certains fichiers n’ont pas pu être mis à la corbeille.", "Suche wird abgebrochen …": "Annulation de la recherche …",
        "{reason}: {count}": "{reason} : {count}", "Zusätzlich: {reasons}": "Également : {reasons}", "Theoretisch einsparbar: {size}": "Économie théorique : {size}",
        "{examined} Bilddateien untersucht · {groups} Duplikatgruppen · {files} mehrfach vorhandene Dateien · {size} theoretisch freigebbar · {skipped} übersprungen oder fehlerhaft": "{examined} fichiers image examinés · {groups} groupes de doublons · {files} fichiers en double · {size} théoriquement libérables · {skipped} ignorés ou défectueux",
    },
    "es": {
        "Doppelte Bilder finden": "Buscar imágenes duplicadas", "Suche läuft …": "Búsqueda en curso …", "Es wurden keine Dateien verändert.": "No se modificó ningún archivo.",
        "Markiere zuerst mindestens eine Datei in der Spalte Papierkorb.": "Primero seleccione al menos un archivo en la columna Papelera.", "Keine Auswahl": "Sin selección", "Es sind keine Dateien für den Papierkorb ausgewählt.": "No hay archivos seleccionados para la papelera.",
        "Dateien in den Papierkorb verschieben": "Mover archivos a la papelera", "Möchtest du die ausgewählten {count} Dateien in den Papierkorb verschieben?\n\nMindestens eine Datei jeder Duplikatgruppe bleibt erhalten.": "¿Quieres mover los {count} archivos seleccionados a la papelera?\n\nSe conservará al menos un archivo de cada grupo de duplicados.",
        "Theoretisch freigebbarer Speicherplatz: {size}": "Espacio recuperable teórico: {size}", "{count} identische Dateien": "{count} archivos idénticos", "Keine doppelten Dateien mehr vorhanden.": "No quedan archivos duplicados.",
        "{groups} verbleibende Duplikatgruppen · {files} verbleibende doppelte Dateien · {size} freigewordener Speicherplatz": "{groups} grupos duplicados restantes · {files} archivos duplicados restantes · {size} de espacio liberado",
        "{count} Datei wurde in den Papierkorb verschoben.": "Se movió {count} archivo a la papelera.", "{count} Dateien wurden in den Papierkorb verschoben.": "Se movieron {count} archivos a la papelera.", "Keine Datei verschoben": "No se movió ningún archivo", "Nicht alle Dateien wurden verschoben": "No se movieron todos los archivos",
        "Keine Datei konnte in den Papierkorb verschoben werden.": "No se pudo mover ningún archivo a la papelera.", "Einige Dateien konnten nicht in den Papierkorb verschoben werden.": "No se pudieron mover algunos archivos a la papelera.", "Suche wird abgebrochen …": "Cancelando búsqueda …",
        "{reason}: {count}": "{reason}: {count}", "Zusätzlich: {reasons}": "También: {reasons}", "Theoretisch einsparbar: {size}": "Ahorro teórico: {size}",
        "{examined} Bilddateien untersucht · {groups} Duplikatgruppen · {files} mehrfach vorhandene Dateien · {size} theoretisch freigebbar · {skipped} übersprungen oder fehlerhaft": "{examined} archivos de imagen examinados · {groups} grupos duplicados · {files} archivos duplicados · {size} recuperables en teoría · {skipped} omitidos o defectuosos",
    },
    "uk": {
        "Doppelte Bilder finden": "Пошук дублікатів зображень", "Suche läuft …": "Триває пошук …", "Es wurden keine Dateien verändert.": "Файли не змінено.",
        "Markiere zuerst mindestens eine Datei in der Spalte Papierkorb.": "Спочатку позначте принаймні один файл у стовпці «Кошик».", "Keine Auswahl": "Немає вибору", "Es sind keine Dateien für den Papierkorb ausgewählt.": "Для кошика не вибрано жодного файлу.",
        "Dateien in den Papierkorb verschieben": "Перемістити файли до кошика", "Möchtest du die ausgewählten {count} Dateien in den Papierkorb verschieben?\n\nMindestens eine Datei jeder Duplikatgruppe bleibt erhalten.": "Перемістити вибрані файли ({count}) до кошика?\n\nБуде збережено щонайменше один файл із кожної групи дублікатів.",
        "Theoretisch freigebbarer Speicherplatz: {size}": "Теоретично вивільнюване місце: {size}", "{count} identische Dateien": "{count} ідентичних файлів", "Keine doppelten Dateien mehr vorhanden.": "Дублікатів файлів більше немає.",
        "{groups} verbleibende Duplikatgruppen · {files} verbleibende doppelte Dateien · {size} freigewordener Speicherplatz": "Залишилося груп дублікатів: {groups} · файлів-дублікатів: {files} · вивільнено: {size}",
        "{count} Datei wurde in den Papierkorb verschoben.": "{count} файл переміщено до кошика.", "{count} Dateien wurden in den Papierkorb verschoben.": "{count} файлів переміщено до кошика.", "Keine Datei verschoben": "Жодного файлу не переміщено", "Nicht alle Dateien wurden verschoben": "Переміщено не всі файли",
        "Keine Datei konnte in den Papierkorb verschoben werden.": "Не вдалося перемістити жодного файлу до кошика.", "Einige Dateien konnten nicht in den Papierkorb verschoben werden.": "Деякі файли не вдалося перемістити до кошика.", "Suche wird abgebrochen …": "Пошук скасовується …",
        "{reason}: {count}": "{reason}: {count}", "Zusätzlich: {reasons}": "Також: {reasons}", "Theoretisch einsparbar: {size}": "Теоретична економія: {size}",
        "{examined} Bilddateien untersucht · {groups} Duplikatgruppen · {files} mehrfach vorhandene Dateien · {size} theoretisch freigebbar · {skipped} übersprungen oder fehlerhaft": "Перевірено файлів зображень: {examined} · груп дублікатів: {groups} · файлів-дублікатів: {files} · теоретично можна вивільнити: {size} · пропущено або пошкоджено: {skipped}",
    },
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"0 Dateien geprüft": "0 files checked", "Alle Markierungen aufheben": "Clear all selections", "Ausgewählte Dateien in den Papierkorb verschieben": "Move selected files to Trash", "Exakt identischer Inhalt": "Exactly identical content", "Noch keine Suche ausgeführt.": "No search has been run yet."},
    "fr": {"0 Dateien geprüft": "0 fichier vérifié", "Alle Markierungen aufheben": "Effacer toutes les sélections", "Ausgewählte Dateien in den Papierkorb verschieben": "Mettre les fichiers sélectionnés à la corbeille", "Exakt identischer Inhalt": "Contenu exactement identique", "Noch keine Suche ausgeführt.": "Aucune recherche n’a encore été effectuée."},
    "es": {"0 Dateien geprüft": "0 archivos comprobados", "Alle Markierungen aufheben": "Borrar todas las selecciones", "Ausgewählte Dateien in den Papierkorb verschieben": "Mover los archivos seleccionados a la papelera", "Exakt identischer Inhalt": "Contenido exactamente idéntico", "Noch keine Suche ausgeführt.": "Aún no se ha realizado ninguna búsqueda."},
    "uk": {"0 Dateien geprüft": "Перевірено 0 файлів", "Alle Markierungen aufheben": "Зняти всі позначення", "Ausgewählte Dateien in den Papierkorb verschieben": "Перемістити вибрані файли до кошика", "Exakt identischer Inhalt": "Точно ідентичний вміст", "Noch keine Suche ausgeführt.": "Пошук ще не виконувався."},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Sucharten": "Search types"},
    "fr": {"Sucharten": "Types de recherche"},
    "es": {"Sucharten": "Tipos de búsqueda"},
    "uk": {"Sucharten": "Типи пошуку"},
}.items():
    CATALOGUE[_code].update(_words)

for _code, _words in {
    "en": {"Ähnlichkeit (dHash)": "Similarity (dHash)", "Hamming-Distanz ≤ {threshold}": "Hamming distance ≤ {threshold}", "BildBlick sucht nach Duplikaten …": "BildBlick is searching for duplicates …", "Bitte warten – dies kann je nach Anzahl der Dateien einige Zeit dauern.": "Please wait — this may take some time depending on the number of files.", "Phase: {phase}": "Phase: {phase}", "Visuelle Ähnlichkeit prüfen": "Checking visual similarity", "Dateien vergleichen": "Comparing files", "Dateien prüfen": "Checking files", "Untersucht: {count} Dateien\nGefunden: {candidates} Kandidaten\nÜbersprungen (fehlerhaft): {skipped}": "Examined: {count} files\nFound: {candidates} candidates\nSkipped (faulty): {skipped}", "Ergebnisse: {groups} Gruppen ({files} Dateien) – {size} freigebbar (theoretisch)": "Results: {groups} groups ({files} files) – {size} reclaimable (theoretical)", "{groups} Gruppen · {files} Dateien · Theoretisch freigebbar: {size}": "{groups} groups · {files} files · Theoretically reclaimable: {size}", "Hamming-Distanz: {distance}": "Hamming distance: {distance}", " (≤ {threshold})": " (≤ {threshold})"},
    "fr": {"Ähnlichkeit (dHash)": "Similarité (dHash)", "Hamming-Distanz ≤ {threshold}": "Distance de Hamming ≤ {threshold}", "BildBlick sucht nach Duplikaten …": "BildBlick recherche des doublons …", "Bitte warten – dies kann je nach Anzahl der Dateien einige Zeit dauern.": "Veuillez patienter : cela peut prendre du temps selon le nombre de fichiers.", "Phase: {phase}": "Phase : {phase}", "Visuelle Ähnlichkeit prüfen": "Vérification de la similarité visuelle", "Dateien vergleichen": "Comparaison des fichiers", "Dateien prüfen": "Vérification des fichiers", "Untersucht: {count} Dateien\nGefunden: {candidates} Kandidaten\nÜbersprungen (fehlerhaft): {skipped}": "Examinés : {count} fichiers\nTrouvés : {candidates} candidats\nIgnorés (défectueux) : {skipped}", "Ergebnisse: {groups} Gruppen ({files} Dateien) – {size} freigebbar (theoretisch)": "Résultats : {groups} groupes ({files} fichiers) – {size} libérables (théorique)", "{groups} Gruppen · {files} Dateien · Theoretisch freigebbar: {size}": "{groups} groupes · {files} fichiers · Libérables en théorie : {size}", "Hamming-Distanz: {distance}": "Distance de Hamming : {distance}", " (≤ {threshold})": " (≤ {threshold})"},
    "es": {"Ähnlichkeit (dHash)": "Similitud (dHash)", "Hamming-Distanz ≤ {threshold}": "Distancia de Hamming ≤ {threshold}", "BildBlick sucht nach Duplikaten …": "BildBlick busca duplicados …", "Bitte warten – dies kann je nach Anzahl der Dateien einige Zeit dauern.": "Espere: esto puede tardar según la cantidad de archivos.", "Phase: {phase}": "Fase: {phase}", "Visuelle Ähnlichkeit prüfen": "Comprobando similitud visual", "Dateien vergleichen": "Comparando archivos", "Dateien prüfen": "Comprobando archivos", "Untersucht: {count} Dateien\nGefunden: {candidates} Kandidaten\nÜbersprungen (fehlerhaft): {skipped}": "Examinados: {count} archivos\nEncontrados: {candidates} candidatos\nOmitidos (defectuosos): {skipped}", "Ergebnisse: {groups} Gruppen ({files} Dateien) – {size} freigebbar (theoretisch)": "Resultados: {groups} grupos ({files} archivos) – {size} recuperables (teórico)", "{groups} Gruppen · {files} Dateien · Theoretisch freigebbar: {size}": "{groups} grupos · {files} archivos · Recuperables en teoría: {size}", "Hamming-Distanz: {distance}": "Distancia de Hamming: {distance}", " (≤ {threshold})": " (≤ {threshold})"},
    "uk": {"Ähnlichkeit (dHash)": "Схожість (dHash)", "Hamming-Distanz ≤ {threshold}": "Відстань Геммінга ≤ {threshold}", "BildBlick sucht nach Duplikaten …": "BildBlick шукає дублікати …", "Bitte warten – dies kann je nach Anzahl der Dateien einige Zeit dauern.": "Будь ласка, зачекайте — залежно від кількості файлів це може зайняти деякий час.", "Phase: {phase}": "Етап: {phase}", "Visuelle Ähnlichkeit prüfen": "Перевірка візуальної схожості", "Dateien vergleichen": "Порівняння файлів", "Dateien prüfen": "Перевірка файлів", "Untersucht: {count} Dateien\nGefunden: {candidates} Kandidaten\nÜbersprungen (fehlerhaft): {skipped}": "Перевірено: {count} файлів\nЗнайдено: {candidates} кандидатів\nПропущено (пошкоджені): {skipped}", "Ergebnisse: {groups} Gruppen ({files} Dateien) – {size} freigebbar (theoretisch)": "Результати: {groups} груп ({files} файлів) — теоретично можна вивільнити {size}", "{groups} Gruppen · {files} Dateien · Theoretisch freigebbar: {size}": "{groups} груп · {files} файлів · Теоретично можна вивільнити: {size}", "Hamming-Distanz: {distance}": "Відстань Геммінга: {distance}", " (≤ {threshold})": " (≤ {threshold})"},
}.items():
    CATALOGUE[_code].update(_words)

def language_code(value: str | None) -> str:
    return value if value in LANGUAGES else "de"

def t(source: str) -> str:
    translated = QCoreApplication.translate("BildBlick", source)
    if translated != source:
        return translated
    return CATALOGUE.get(_language, {}).get(source, source)

class LanguageManager(QObject):
    def __init__(self, settings: QSettings) -> None:
        super().__init__()
        self.settings = settings
        self.set_language(settings.value(LANGUAGE_KEY, "de", type=str), persist=False)

    @property
    def code(self) -> str: return _language

    def set_language(self, code: str, *, persist: bool = True) -> None:
        global _language
        _language = language_code(code)
        if persist:
            self.settings.setValue(LANGUAGE_KEY, _language); self.settings.sync()
        app = QApplication.instance()
        if app:
            for widget in app.topLevelWidgets():
                self.translate_widget_tree(widget)

    def translate_widget_tree(self, root: QWidget) -> None:
        for widget in [root, *root.findChildren(QWidget)]:
            if isinstance(widget, (QDialog, QMainWindow)):
                source = widget.property("bildblickSourceWindowTitle") or widget.windowTitle()
                if source:
                    widget.setProperty("bildblickSourceWindowTitle", source); widget.setWindowTitle(t(source))
            if isinstance(widget, (QLabel, QPushButton, QToolButton, QCheckBox)):
                source = widget.property("bildblickSourceText") or widget.text()
                widget.setProperty("bildblickSourceText", source); widget.setText(t(source))
            elif isinstance(widget, QGroupBox):
                source = widget.property("bildblickSourceTitle") or widget.title()
                widget.setProperty("bildblickSourceTitle", source); widget.setTitle(t(source))
            tooltip = widget.property("bildblickSourceToolTip") or widget.toolTip()
            if tooltip:
                widget.setProperty("bildblickSourceToolTip", tooltip); widget.setToolTip(t(tooltip))
            if isinstance(widget, QComboBox):
                sources = widget.property("bildblickSourceItems")
                if not sources:
                    sources = [widget.itemText(index) for index in range(widget.count())]
                    widget.setProperty("bildblickSourceItems", sources)
                for index, source in enumerate(sources):
                    widget.setItemText(index, t(source))
        for action in root.findChildren(QAction):
            source = action.property("bildblickSourceText") or action.text()
            action.setProperty("bildblickSourceText", source); action.setText(t(source))
            tooltip = action.property("bildblickSourceToolTip") or action.toolTip()
            if tooltip:
                action.setProperty("bildblickSourceToolTip", tooltip); action.setToolTip(t(tooltip))
        for menu in root.findChildren(QMenu):
            source = menu.property("bildblickSourceTitle") or menu.title()
            menu.setProperty("bildblickSourceTitle", source); menu.setTitle(t(source))
